version: '3.7'

services:
    # Load balancer
    nginx:
        build: ./nginx
        container_name: nginx_gateway
        restart: always
        links:
            - server
            - client
        depends_on:
            - server
            - client
        ports:
            - '8000:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d

    # mongodb
    db:
        image: mongo
        container_name: db
        restart: always
        command: mongod
        expose:
            - 27017

    # React app
    client:
        container_name: client
        build: ./client
        restart: always
        environment:
            - CI=true
            - NODE_ENV=development
        expose:
            - 3000
        volumes:
            - ./client:/app

    # Backend
    server:
        build: ./server
        container_name: server
        restart: always
        links:
            - db
        depends_on:
            - db
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=creds.json
            - MONGO_URI=mongodb://db:27017/db
        expose:
            - 5000
        volumes:
            - ./server:/app
