version: '3.7'

services:
    # Load balancer
    nginx:
        build: ./nginx
        container_name: nginx_gateway
        restart: always
        links:
            - server
            - client
            - flower
            - docs
        depends_on:
            - server
            - client
            - flower
            - docs
        ports:
            - '8000:80'
    # Swagger API spec
    docs:
        build: ./docs
        container_name: docs
        restart: always
        expose:
            - 3000
    # Mongodb
    db:
        image: mongo
        container_name: db
        restart: always
        command: mongod
        expose:
            - 27017

    # Redis message queue
    redis_queue:
        image: redis
        container_name: redis_queue
        restart: always
        expose:
            - 6379

    # React client
    client:
        container_name: client
        build: ./client
        restart: always
        environment:
            - CI=true
            - NODE_ENV=development
        expose:
            - 3000
        volumes:
            - ./client/src:/app/src

    # Flask backend
    server:
        build: ./server
        container_name: server
        restart: always
        links:
            - db
            - redis_queue
        depends_on:
            - db
            - redis_queue
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=creds.json
            - MONGO_URI=mongodb://db:27017/db
            - REDIS_URI=redis://redis_queue:6379/0
        expose:
            - 5000
        volumes:
            - ./server:/app

    # Celery worker
    worker:
        build: ./server
        command: ['celery', '-A', 'worker.celery', 'worker', '-l', 'INFO']
        container_name: worker
        restart: always
        links:
            - db
            - redis_queue
        depends_on:
            - db
            - redis_queue
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=creds.json
            - MONGO_URI=mongodb://db:27017/db
            - REDIS_URI=redis://redis_queue:6379/0

    # Flower dashboard for celery
    flower:
        build: ./server
        container_name: flower
        command:
            [
                'flower',
                '--app=worker.celery',
                '--broker=redis://redis_queue:6379/0',
                '--url_prefix=flower',
            ]
        expose:
            - 5555
        environment:
            - MONGO_URI=mongodb://db:27017/db
            - REDIS_URI=redis://redis_queue:6379/0
        depends_on:
            - client
            - redis_queue
            - worker
