import { useHistory } from 'react-router';
import styled from 'styled-components';

const Container = styled.div`
    display: flex;
`;

const Button = styled.button`
    margin: 10px;
    width: 350px;
    height: 400px;
`;

const SelectInterviewType = () => {
    const history = useHistory();

    const selectOneWayInterview = () => {
        console.log('one way');
        history.push('/choosequestions');
    };

    const selectPairInterview = () => {
        console.log('pair');
    };

    return (
        <Container>
            <Button onClick={selectOneWayInterview}>
                <h5>One Way Interview</h5>
                <p>
                    Conduct a one way interview to practice your interview skills. You
                    will be prompted with questions and receive insights generated by AI.
                </p>
            </Button>
            <Button onClick={selectPairInterview}>
                <h5>Paired Peer Interview </h5>
                <p>
                    Tell us when you want to practice and get paired with an optimal peer.
                    Conduct mock interviews with each other. At the end of the session you
                    will both receive peer feedback along with insights generated by AI.
                </p>
            </Button>
        </Container>
    );
};

export default SelectInterviewType;
